// The Pathways Within clinician roster, sourced from the live site
// (pathwayswithin.me/clinicians) and cleaned to the Eastern Keel copy rules
// (no em or en dashes, no hyphens in prose, no AI filler). Bios are the
// clinicians' own words, lightly normalised, never invented.
//
// Relations are expressed as slug arrays that the seed connects:
//   conditions / modalities / populations  -> the taxonomy a clinician treats
//   offices                                -> the locations a clinician serves
//
// IMPORTANT (flag to client): per clinician office assignments are PROVISIONAL.
// The live site states regions only for the two clinical directors (Nassau,
// Suffolk) and a practice wide role for the founder. The remaining office links
// are a reasonable distribution so each location shows a real roster; confirm
// the true rosters with the practice before relying on them for local listings.

export type ClinicianSeed = {
  slug: string;
  name: string;
  credentials?: string;
  title?: string;
  bio: string;
  offices: string[];
  conditions: string[];
  modalities: string[];
  populations: string[];
};

const ALL_OFFICES = [
  "smithtown",
  "garden-city",
  "massapequa",
  "port-jefferson",
  "rockville-centre",
];

export const clinicians: ClinicianSeed[] = [
  {
    slug: "rachel-lessard",
    name: "Rachel Lessard",
    credentials: "LCSW-R",
    title: "Founder",
    bio: "Together we can explore your experiences and help you feel safe and secure again. In my office, with or without your loved one, we can develop new styles of communication that create the relationship you have always wanted.",
    offices: ALL_OFFICES,
    conditions: ["anxiety", "depression", "ptsd", "panic-and-phobias", "ocd"],
    modalities: ["hypnotherapy", "emdr", "gottman-couples"],
    populations: ["couples", "veterans", "first-responders", "adults"],
  },
  {
    slug: "ksusha-cascio",
    name: "Ksusha Cascio",
    credentials: "LCSW",
    title: "Chief Operating Officer",
    bio: "Reaching out for help can feel daunting, but nothing happens in our comfort or discomfort zone. I am here to provide a judgment free safe space to explore, challenge, and develop the best version of yourself.",
    offices: ["smithtown", "garden-city"],
    conditions: ["complex-ptsd", "adhd"],
    modalities: ["ifs"],
    populations: ["adults", "professionals"],
  },
  {
    slug: "joe-bush",
    name: "Joe Bush",
    credentials: "LCSW",
    title: "Clinical Director, Nassau",
    bio: "You do not have to go through this alone. In my sessions, I strive to create a warm and empathetic environment, free of judgment, where we can safely explore life challenges together.",
    offices: ["garden-city", "massapequa", "rockville-centre"],
    conditions: ["anxiety", "depression", "bipolar-disorder", "adhd", "ocd"],
    modalities: [],
    populations: ["teens", "college-students", "families", "adults"],
  },
  {
    slug: "lee-wasser",
    name: "Lee Wasser",
    credentials: "LMHC-D",
    title: "Clinical Director, Suffolk",
    bio: "The world is a very diverse place. Every person is different and comes from a different perspective. I am skilled in a variety of backgrounds and clinical approaches, and I continually work to build my toolbox for treatment. As a counselor, I want you to embrace your individuality as we work together to see what works best for you.",
    offices: ["smithtown", "port-jefferson"],
    conditions: [
      "trauma",
      "depression",
      "self-harm",
      "anxiety",
      "substance-use",
      "life-transitions",
      "domestic-violence-recovery",
    ],
    modalities: ["emdr", "cognitive-processing"],
    populations: ["lgbtqia", "teens", "adults"],
  },
  {
    slug: "kaitlyn-kelly",
    name: "Kaitlyn Kelly",
    credentials: "LMHC",
    title: "Supervisor",
    bio: "Therapy is for everyone. In a session with me, you can expect a genuine zone free of judgment where you can feel comfortable to share openly and honestly. Beginning your mental health journey can be intimidating, but it does not have to be scary. I look forward to working with you and helping you meet your individual goals in therapy.",
    offices: ["massapequa", "rockville-centre"],
    conditions: ["anxiety", "depression", "grief", "panic-and-phobias", "insomnia"],
    modalities: ["talk-therapy"],
    populations: ["teens", "adults"],
  },
  {
    slug: "laura-desilva",
    name: "Laura DeSilva",
    credentials: "LMHC",
    title: "Supervisor",
    bio: "As an eclectic clinician, I draw on humanistic, cognitive behavioral, and psychodynamic frameworks to suit each client's needs. I view counseling as a collaboration between therapist and client, and I take a person centered approach to the process. I bring warmth, genuineness, and acceptance to the therapeutic relationship so my clients feel safe and supported to grow and change.",
    offices: ["garden-city", "smithtown"],
    conditions: ["anxiety", "trauma", "depression", "grief"],
    modalities: ["cbt", "cognitive-processing"],
    populations: ["adults"],
  },
  {
    slug: "samantha-juravich",
    name: "Samantha Juravich",
    credentials: "LCSW",
    title: "Supervisor",
    bio: "My first goal as a therapist is to create a safe space and a supportive environment that helps clients with self discovery, change, and improving their quality of life. I provide treatment that is effective, inclusive, and functional. I tailor each session to the client's individual needs, drawing on a variety of therapeutic techniques and collaborating with other treatment providers when needed.",
    offices: ["smithtown", "port-jefferson"],
    conditions: ["trauma", "anxiety", "depression", "adhd"],
    modalities: ["play-therapy"],
    populations: ["children", "teens", "families"],
  },
  {
    slug: "benjamin-marmorstein",
    name: "Benjamin Marmorstein",
    credentials: "LCSW",
    bio: "Welcome to a compassionate and creative approach to some of life's difficult challenges. Together we create a safe space of unwavering support, free of judgment, where we can explore your thoughts and feelings openly. I help clients uncover their inner strengths and navigate life's challenges with resilience and confidence. Whether we are working through past trauma or pursuing personal growth, we build an individualized plan for your healing.",
    offices: ["massapequa", "rockville-centre"],
    conditions: ["complex-ptsd", "anxiety", "depression", "adhd", "trauma"],
    modalities: [],
    populations: ["children", "teens", "families"],
  },
  {
    slug: "beth-gabellini",
    name: "Beth Gabellini",
    credentials: "LCSW",
    bio: "My philosophy is that we are all perfectly imperfect and should seek to live as our authentic selves. I am an open, caring professional who will not judge you. Instead, I give you the space to feel safe, be heard, and work through your thoughts and emotions.",
    offices: ["garden-city", "rockville-centre"],
    conditions: ["life-transitions"],
    modalities: [],
    populations: ["veterans", "adults", "couples"],
  },
  {
    slug: "carly-sandstrom",
    name: "Carly Sandstrom",
    credentials: "LMHC",
    bio: "In therapy there is no one approach that fits everyone. Using an eclectic approach, I tailor each session to be the most beneficial for you on your journey with mental health. You can expect a warm, trusting, and empathetic environment where we can safely work through life's problems and joys. I believe in the power of a strong, compassionate therapeutic relationship, and we will work together to find relief and create positive change.",
    offices: ["smithtown", "massapequa"],
    conditions: ["trauma", "anxiety"],
    modalities: ["ifs", "emdr"],
    populations: ["veterans", "first-responders"],
  },
  {
    slug: "jen-brooks",
    name: "Jen Brooks",
    credentials: "LCSW",
    bio: "Life can hand us many challenges, but you are not alone. I provide a balance of support, understanding, and compassion on your journey of growth. Virtually or in office, we can work together to solve problems and practice skills that help you feel in control of your life again and reach your goals.",
    offices: ["port-jefferson", "smithtown"],
    conditions: ["anxiety", "depression", "trauma", "adhd"],
    modalities: [],
    populations: ["adults", "teens"],
  },
  {
    slug: "lauren-hollander",
    name: "Lauren Hollander",
    credentials: "LCSW",
    bio: "I focus on bringing a client's mind, body, spirit, and emotions into the healing process. We move toward healing and growth in a safe space, free of judgment, that I create together with my clients.",
    offices: ["garden-city", "massapequa"],
    conditions: ["trauma", "ptsd", "depression", "anxiety", "bipolar-disorder", "bpd"],
    modalities: ["somatic-therapy", "emdr", "dbt"],
    populations: ["adults"],
  },
  {
    slug: "paula-gonthier",
    name: "Paula Gonthier",
    credentials: "LCSW",
    bio: "I help you reach your own strengths and talents to recognize and remove the roadblocks that keep you from achieving your goals and living your ideal life. We will rediscover hope and meaning, and you will learn to approach challenges with calm and self assurance.",
    offices: ["rockville-centre", "garden-city"],
    conditions: ["life-transitions"],
    modalities: ["gottman-couples"],
    populations: ["couples", "adults"],
  },
  {
    slug: "samantha-tavel",
    name: "Samantha Tavel",
    credentials: "LMFT",
    bio: "I believe that everyone can benefit from therapy. When you come to see me, you can expect an open and safe space where you feel free to be yourself. I use a relaxed CBT approach tailored to you and your unique goals, with honest and unconditional support. I look forward to beginning this journey with you.",
    offices: ["massapequa", "port-jefferson"],
    conditions: ["anxiety", "trauma", "adhd"],
    modalities: ["cbt", "gottman-couples"],
    populations: ["adults", "teens", "couples", "families"],
  },
  {
    slug: "tia-baumohl",
    name: "Tia Baumohl",
    title: "Energy Work and Coaching",
    bio: "After more than a decade supporting mothers and their partners through pregnancy and labor, I am seasoned at supporting people during life's most transformative moments. With over five years in energy work and coaching, I help individuals and couples navigate challenging dynamics, find breakthroughs, and uncover untapped potential. Trained in modalities shown to ease symptoms of anxiety, depression, and nervous system dysregulation, I offer focused support for relationship growth, clear communication, and personal change.",
    offices: ["garden-city"],
    conditions: ["anxiety", "depression"],
    modalities: ["ifs"],
    populations: ["couples", "adults"],
  },
  {
    slug: "anna-ostrow",
    name: "Anna Ostrow",
    credentials: "MHC-LP",
    bio: "Life can be overwhelming, but you do not have to go through it alone. I create a warm, supportive space, free of judgment, where you can feel safe to be yourself. Whether you are feeling anxious, overwhelmed, or just trying to make sense of things, we will explore what is coming up for you and find ways to move forward. My goal is to help you feel heard, understood, and a little more grounded with each step.",
    offices: ["smithtown", "rockville-centre"],
    conditions: ["anxiety", "depression", "life-transitions", "grief"],
    modalities: ["talk-therapy"],
    populations: ["teens", "adults", "college-students"],
  },
  {
    slug: "charity-meyer",
    name: "Charity (Valen) Meyer",
    credentials: "MFT-LP",
    bio: "Every person's journey is unique. My passion is to create a safe, warm space, free of judgment, where you feel truly heard and understood. I meet you with compassion wherever you are on your path, adapting my approach to help you reframe your story, develop practical solutions, and feel empowered to make meaningful change.",
    offices: ["garden-city", "massapequa"],
    conditions: ["substance-use", "depression", "anxiety", "bipolar-disorder"],
    modalities: [],
    populations: ["lgbtqia", "adults", "couples"],
  },
  {
    slug: "chelsea-bell",
    name: "Chelsea Bell",
    credentials: "LMSW",
    bio: "Taking the first step to seek help can be difficult yet rewarding. My goal is to create a comfortable environment, free of judgment and unique to you. Together we explore your goals and overcome life's challenges.",
    offices: ["port-jefferson", "smithtown"],
    conditions: ["anxiety", "depression", "trauma"],
    modalities: ["talk-therapy"],
    populations: ["adults"],
  },
  {
    slug: "frank-tropeano",
    name: "Frank Tropeano",
    credentials: "LMSW",
    bio: "Life can sometimes feel overwhelming, but you do not have to go through those times alone. I create an open space where clients feel safe and supported as they work through challenges. Together, we work toward the best version of yourself.",
    offices: ["massapequa", "rockville-centre"],
    conditions: ["anxiety", "depression"],
    modalities: ["gottman-couples", "talk-therapy"],
    populations: ["couples", "adults"],
  },
  {
    slug: "juliette-squicciarini",
    name: "Juliette Squicciarini",
    credentials: "LMSW",
    bio: "The thought of therapy can be intimidating. That is why I am committed to creating a positive, uplifting, and safe space where you feel seen and heard. Together we work through life experiences in a supportive environment where you can heal and grow. You are not alone on this journey. I am here with you every step of the way.",
    offices: ["smithtown", "garden-city"],
    conditions: ["anxiety", "depression", "substance-use"],
    modalities: ["talk-therapy"],
    populations: ["teens", "adults"],
  },
  {
    slug: "kathleen-dimartino",
    name: "Kathleen Dimartino",
    credentials: "LMSW",
    bio: "The challenges we face in life can feel overwhelming at times. Therapy is often a good place to start, or continue, when we need some extra support. Together we can navigate life's difficulties and help you feel better.",
    offices: ["rockville-centre", "port-jefferson"],
    conditions: ["bpd", "self-harm", "depression", "anxiety"],
    modalities: ["dbt"],
    populations: ["adults"],
  },
  {
    slug: "lindsay-laier",
    name: "Lindsay Laier",
    credentials: "MFT-LP",
    bio: "Life is a cycle, and change can bring many challenges. In therapy I work with individuals, families, and couples to provide insight and perspective on the challenges life puts in our paths. Together we set goals for therapy and build the tools needed to bring positive change in a relaxed environment, free of judgment.",
    offices: ["garden-city", "massapequa"],
    conditions: ["life-transitions"],
    modalities: [],
    populations: ["families", "couples", "teens", "adults"],
  },
  {
    slug: "maddy-zambri",
    name: "Maddy Zambri",
    credentials: "MHC-LP",
    bio: "Life is full of changes and challenges that touch many parts of our lives. Reaching out for help during these times is often a struggle in itself, but no destination is reached without the first step. I want to help you take that step by providing a safe environment, free of judgment, to explore your life and regain balance and harmony through the many changes life brings.",
    offices: ["smithtown", "port-jefferson"],
    conditions: ["life-transitions", "substance-use", "anxiety"],
    modalities: [],
    populations: ["lgbtqia", "adults"],
  },
  {
    slug: "mariah-simone",
    name: "Mariah Simone",
    credentials: "MHC-LP",
    bio: "My goal as a therapist is to help you feel safe, heard, and comfortable while working toward your goals. My approach is eclectic, drawing on mindfulness, cognitive behavioral, and psychodynamic approaches to help you reach your unique goals and guide you through your personal healing. In our time together you will always be met with unconditional positive regard and true support.",
    offices: ["rockville-centre", "massapequa"],
    conditions: ["anxiety", "depression", "insomnia", "panic-and-phobias"],
    modalities: ["cbt"],
    populations: ["teens", "college-students"],
  },
  {
    slug: "nicole-duffy",
    name: "Nicole Duffy",
    credentials: "LMSW",
    bio: "Everyone should feel comfortable, safe, and understood. With a person centered approach, I meet you where you are. Each session is tailored to your goals and to identifying the skills that move you toward change. Together we work through life's unique challenges.",
    offices: ["garden-city", "smithtown"],
    conditions: ["domestic-violence-recovery", "trauma"],
    modalities: [],
    populations: ["adults"],
  },
];
